name: Build and attest Docker Image

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch:

jobs:
  BuildingAndScanningAppImage:
    runs-on: ubuntu-latest

    steps:

    - name: Build Docker image
      run: |
        echo $pwd
        ls
        docker build -t ghcr.io/${{ github.repository_owner }}/sharang-app:latest .

        DIGEST=$(docker inspect --format='{{index .Id}}' ghcr.io/${{ github.repository_owner }}/sharang-app:latest)
        echo "DIGEST=$DIGEST" >> $GITHUB_ENV

    - name: Log in to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_SEC }}

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Check install!
      run: cosign version
  

    - name: Push Container image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/sharang-app:latest